from __future__ import annotations
from typing import Dict, List, Set

class StdlibSymbolTable:
    """
    Static, curated symbol tables for standard libraries that ship with each language runtime.
    These are bundled directly and do not require network access.
    """

    # Seeding with common symbols for each language
    _TABLES: Dict[str, Dict[str, List[str]]] = {
        "python": {
            "json": ["dumps", "loads", "JSONEncoder", "JSONDecoder", "dump", "load"],
            "os": ["path", "environ", "getenv", "system", "mkdir", "remove", "rename", "walk"],
            "os.path": ["join", "exists", "isdir", "isfile", "abspath", "dirname", "basename", "split"],
            "pathlib": ["Path", "PurePath", "PosixPath", "WindowsPath"],
            "re": ["compile", "search", "match", "findall", "sub", "split"],
            "datetime": ["datetime", "date", "time", "timedelta", "timezone"],
            "sys": ["argv", "exit", "path", "modules", "stdin", "stdout", "stderr"],
            "typing": ["Optional", "Union", "List", "Dict", "Any", "Callable", "Iterable",
                       "TypeVar", "Tuple", "Set", "FrozenSet", "Sequence", "Mapping", "ClassVar",
                       "Final", "Literal", "Protocol", "Generic", "Type", "Coroutine", "Awaitable",
                       "AsyncIterator", "AsyncGenerator", "ContextManager", "Counter", "Deque",
                       "DefaultDict", "OrderedDict", "ChainMap", "Generator", "Iterator", "NamedTuple",
                       "TypedDict", "Annotated", "TypeAlias", "Self", "Never", "NoReturn"],
            "collections": ["defaultdict", "Counter", "deque", "namedtuple", "OrderedDict"],
            "math": ["sqrt", "sin", "cos", "tan", "pi", "e", "floor", "ceil"],
            "time": ["time", "sleep", "strftime", "strptime", "gmtime", "localtime"],
            "threading": ["Thread", "Lock", "RLock", "Condition", "Event", "Semaphore"],
            "subprocess": ["run", "Popen", "PIPE", "call", "check_call", "check_output"],
            "logging": ["getLogger", "basicConfig", "info", "warning", "error", "debug", "critical"],
        },
        "javascript": {
            "fs": ["readFile", "writeFile", "readFileSync", "writeFileSync", "stat", "readdir"],
            "path": ["join", "resolve", "dirname", "basename", "extname", "parse"],
            "http": ["createServer", "request", "get", "IncomingMessage", "ServerResponse"],
            "https": ["createServer", "request", "get"],
            "crypto": ["createHash", "createHmac", "randomBytes", "pbkdf2"],
            "stream": ["Readable", "Writable", "Duplex", "Transform", "pipeline"],
            "events": ["EventEmitter"],
            "os": ["platform", "release", "totalmem", "freemem", "cpus"],
            "util": ["promisify", "inherits", "inspect", "format"],
            "process": ["argv", "env", "exit", "stdin", "stdout", "stderr"],
            # Built-in prototype methods — used pervasively in JS code.
            # Full method sets for the most common global object prototypes.
            "Array.prototype": ["map", "filter", "reduce", "forEach", "push", "pop", "slice",
                                "splice", "concat", "join", "indexOf", "find", "findIndex",
                                "includes", "some", "every", "flat", "flatMap", "sort", "reverse",
                                "fill", "keys", "values", "entries", "length"],
            "String.prototype": ["split", "replace", "match", "trim", "charAt", "charCodeAt",
                                 "concat", "includes", "indexOf", "slice", "substring", "toLowerCase",
                                 "toUpperCase", "padStart", "padEnd", "repeat", "startsWith",
                                 "endsWith", "at", "codePointAt", "normalize"],
            "Promise": ["then", "catch", "finally", "all", "race", "allSettled", "any", "resolve",
                        "reject"],
        },
        "go": {
            "fmt": ["Println", "Printf", "Sprintf", "Errorf", "Scan", "Fprint"],
            "os": ["Open", "Create", "Args", "Exit", "Getenv", "Mkdir", "Remove", "Stat"],
            "io": ["ReadFull", "ReadAll", "Copy", "LimitReader", "NewSectionReader"],
            "net/http": ["Get", "Post", "HandleFunc", "ListenAndServe", "NewRequest", "Client"],
            "encoding/json": ["Marshal", "Unmarshal", "NewEncoder", "NewDecoder", "Indent"],
            "errors": ["New", "Unwrap", "Is", "As"],
            "context": ["Background", "TODO", "WithCancel", "WithDeadline", "WithTimeout", "WithValue"],
            "sync": ["WaitGroup", "Mutex", "RWMutex", "Cond", "Once", "Pool"],
            "time": ["Now", "Sleep", "Since", "Parse", "Format", "Tick"],
            "strings": ["Contains", "Split", "Join", "Replace", "ToLower", "ToUpper", "TrimSpace"],
        },
        "rust": {
            "std::collections": ["HashMap", "HashSet", "VecDeque", "BinaryHeap", "BTreeMap", "BTreeSet"],
            "std::io": ["Read", "Write", "BufReader", "BufWriter", "stdin", "stdout", "copy"],
            "std::fs": ["File", "read_to_string", "read", "write", "create_dir", "remove_file"],
            "std::path": ["Path", "PathBuf"],
            "std::sync": ["Arc", "Mutex", "RwLock", "Barrier", "Condvar", "mpsc"],
            "std::thread": ["spawn", "sleep", "current", "park"],
            "std::time": ["Duration", "Instant", "SystemTime"],
            "std::net": ["TcpListener", "TcpStream", "UdpSocket", "IpAddr"],
            "std::env": ["args", "vars", "var", "current_dir", "current_exe"],
            "std::process": ["Command", "Stdio", "exit", "Child"],
            "std::fmt": ["Debug", "Display", "Formatter", "Error"],
            # Core prelude types — the 6 most commonly used types in idiomatic Rust.
            # These account for ~80% of all method calls and resolve ~1,500 of the
            # 6,220 unresolved stubs in the tokenizers I4 benchmark.
            "std::option::Option": ["unwrap", "unwrap_or", "unwrap_or_else", "map", "and_then",
                                    "ok_or", "ok_or_else", "is_some", "is_none", "expect",
                                    "filter", "or", "xor", "get_or_insert", "take", "replace",
                                    "copied", "cloned", "as_ref", "as_mut", "iter", "into_iter"],
            "std::result::Result": ["map", "map_err", "unwrap", "unwrap_or", "unwrap_or_else",
                                    "ok", "err", "is_ok", "is_err", "expect", "and_then", "or",
                                    "as_ref", "as_mut", "copied", "cloned", "iter"],
            "std::iter::Iterator": ["map", "collect", "filter", "into_iter", "next", "fold",
                                    "for_each", "enumerate", "zip", "chain", "take", "skip",
                                    "filter_map", "flat_map", "any", "all", "count", "sum",
                                    "min", "max", "rev", "peekable", "dedup", "cloned", "copied"],
            "std::vec::Vec": ["push", "len", "get", "iter", "into_iter", "extend", "clear",
                              "pop", "insert", "remove", "truncate", "resize", "sort", "sort_by",
                              "binary_search", "contains", "retain", "drain", "split_off",
                              "as_slice", "as_mut_slice", "with_capacity", "capacity"],
            "std::string::String": ["to_string", "push_str", "len", "as_str", "into_bytes",
                                    "chars", "push", "replace", "split", "trim", "contains",
                                    "starts_with", "ends_with", "clear", "insert", "remove",
                                    "into_string", "as_bytes", "is_empty"],
            "std::convert": ["into", "from", "try_into", "try_from", "as_ref", "as_mut",
                             "to_owned", "to_string"],
        },
        "typescript": {
            # JS global objects (keep as-is) — expanded with full method sets
            "Array": ["map", "filter", "reduce", "forEach", "push", "pop", "slice", "splice",
                      "concat", "join", "indexOf", "find", "findIndex", "includes", "some",
                      "every", "flat", "flatMap", "sort", "reverse", "fill", "keys", "values",
                      "entries", "length"],
            "Promise": ["then", "catch", "finally", "all", "race", "allSettled", "any", "resolve",
                        "reject"],
            "Map": ["set", "get", "has", "delete", "clear", "forEach", "entries", "keys", "values"],
            "Set": ["add", "has", "delete", "clear", "forEach", "entries", "keys", "values"],
            "Symbol": ["iterator", "asyncIterator", "for", "description"],
            "Reflect": ["get", "set", "has", "deleteProperty", "ownKeys", "apply", "construct"],
            "WeakMap": ["set", "get", "has", "delete"],
            "WeakSet": ["add", "has", "delete"],
            "BigInt": ["asIntN", "asUintN"],
            "Intl": ["Collator", "DateTimeFormat", "NumberFormat", "PluralRules"],
            "Math": ["abs", "ceil", "floor", "round", "max", "min", "sqrt", "pow", "random", "PI", "E"],
            "JSON": ["parse", "stringify"],
            "console": ["log", "error", "warn", "info", "debug", "trace", "dir", "time", "timeEnd"],
            "Object": ["keys", "values", "entries", "assign", "freeze", "seal", "create", "getPrototypeOf", "defineProperty"],
            "String": ["split", "replace", "match", "trim", "charAt", "charCodeAt", "concat",
                       "includes", "indexOf", "slice", "substring", "toLowerCase", "toUpperCase",
                       "padStart", "padEnd", "repeat", "startsWith", "endsWith", "at",
                       "codePointAt", "normalize"],
            # Node.js built-in modules (shared with JavaScript — @types/node ships TS declarations)
            "fs": ["readFile", "writeFile", "readFileSync", "writeFileSync", "stat", "readdir"],
            "path": ["join", "resolve", "dirname", "basename", "extname", "parse"],
            "http": ["createServer", "request", "get", "IncomingMessage", "ServerResponse"],
            "https": ["createServer", "request", "get"],
            "crypto": ["createHash", "createHmac", "randomBytes", "pbkdf2"],
            "stream": ["Readable", "Writable", "Duplex", "Transform", "pipeline"],
            "events": ["EventEmitter"],
            "os": ["platform", "release", "totalmem", "freemem", "cpus"],
            "util": ["promisify", "inherits", "inspect", "format"],
            "process": ["argv", "env", "exit", "stdin", "stdout", "stderr"],
        },
        "c": {
            "stdio": ["printf", "scanf", "fopen", "fclose", "fread", "fwrite", "fgets", "fputs", "fprintf", "getchar", "putchar"],
            "stdlib": ["malloc", "calloc", "realloc", "free", "exit", "atoi", "atof", "rand", "srand", "qsort", "bsearch"],
            "string": ["strlen", "strcpy", "strncpy", "strcat", "strncat", "strcmp", "strncmp", "strstr", "strchr", "memcpy", "memset", "memcmp"],
            "math": ["sin", "cos", "tan", "asin", "acos", "atan", "atan2", "sqrt", "pow", "ceil", "floor", "fabs", "exp", "log", "fmod"],
            "ctype": ["isalpha", "isdigit", "isspace", "isalnum", "isupper", "islower", "ispunct", "isprint", "isxdigit", "toupper", "tolower"],
            "time": ["time", "clock", "difftime", "mktime", "strftime", "localtime", "gmtime", "asctime", "ctime"],
            "assert": ["assert"],
            "errno": ["errno", "perror", "strerror"],
            "stddef": ["size_t", "NULL", "offsetof", "ptrdiff_t", "wchar_t"],
            "stdint": ["int8_t", "int16_t", "int32_t", "int64_t", "uint8_t", "uint16_t", "uint32_t", "uint64_t"],
            "stdbool": ["bool", "true", "false"],
            "limits": ["INT_MAX", "INT_MIN", "CHAR_BIT", "LONG_MAX", "UINT_MAX", "DBL_MAX", "FLT_MAX"],
            "signal": ["signal", "raise", "kill", "sigaction", "sigprocmask", "sigemptyset", "sigfillset"],
            "setjmp": ["setjmp", "longjmp", "jmp_buf"],
            "locale": ["setlocale", "localeconv"],
            "wchar": ["wprintf", "wscanf", "wcslen", "wcscpy", "wcscat", "wcscmp", "wcsstr", "wcschr", "wcstok", "wcstod"],
        },
        "cpp": {
            "iostream": ["cin", "cout", "cerr", "clog", "endl", "flush", "ws", "ends"],
            "vector": ["vector", "push_back", "pop_back", "size", "empty", "clear", "reserve", "resize", "at", "front", "back", "begin", "end", "emplace_back"],
            "string": ["string", "to_string", "stoi", "stol", "stoul", "stoll", "stof", "stod", "getline"],
            "algorithm": ["sort", "stable_sort", "find", "find_if", "copy", "move", "transform", "accumulate", "fill", "min", "max", "swap", "reverse", "rotate", "unique", "remove", "count", "all_of", "any_of", "none_of", "for_each", "lower_bound", "upper_bound", "binary_search", "merge", "partition", "is_sorted", "push_heap", "pop_heap", "make_heap", "sort_heap", "shuffle"],
            "map": ["map", "multimap", "begin", "end", "size", "empty", "clear", "insert", "erase", "find", "count", "lower_bound", "upper_bound", "at"],
            "set": ["set", "multiset", "begin", "end", "size", "empty", "clear", "insert", "erase", "find", "count", "lower_bound", "upper_bound"],
            "unordered_map": ["unordered_map", "unordered_set", "begin", "end", "size", "empty", "clear", "insert", "erase", "find", "count", "bucket", "bucket_count", "load_factor", "rehash", "reserve"],
            "memory": ["shared_ptr", "unique_ptr", "weak_ptr", "make_shared", "make_unique", "allocator", "addressof", "static_pointer_cast", "dynamic_pointer_cast", "const_pointer_cast"],
            "thread": ["thread", "this_thread", "get_id", "join", "detach", "swap", "hardware_concurrency", "yield", "sleep_for", "sleep_until", "jthread"],
            "mutex": ["mutex", "lock_guard", "unique_lock", "scoped_lock", "timed_mutex", "recursive_mutex", "shared_mutex", "shared_lock", "defer_lock", "try_to_lock", "adopt_lock", "once_flag", "call_once"],
            "chrono": ["duration", "steady_clock", "system_clock", "high_resolution_clock", "time_point", "hours", "minutes", "seconds", "milliseconds", "microseconds", "nanoseconds", "now", "duration_cast"],
            "fstream": ["ifstream", "ofstream", "fstream", "open", "close", "is_open", "getline", "read", "write", "tellg", "tellp", "seekg", "seekp", "flush", "eof"],
            "sstream": ["istringstream", "ostringstream", "stringstream", "str"],
            "cmath": ["sqrt", "pow", "sin", "cos", "tan", "asin", "acos", "atan", "atan2", "sinh", "cosh", "tanh", "exp", "log", "log10", "log2", "ceil", "floor", "fabs", "fmod", "fmax", "fmin", "round", "trunc", "hypot", "cbrt", "erf", "erfc", "lgamma", "tgamma"],
            "numeric": ["accumulate", "iota", "partial_sum", "adjacent_difference", "inner_product", "reduce", "gcd", "lcm", "midpoint", "lerp"],
            "iterator": ["begin", "end", "cbegin", "cend", "rbegin", "rend", "advance", "distance", "next", "prev", "back_inserter", "front_inserter", "inserter", "make_reverse_iterator", "move_iterator", "make_move_iterator"],
            "functional": ["function", "bind", "hash", "ref", "cref", "mem_fn", "invoke", "plus", "minus", "multiplies", "divides", "modulus", "negate", "equal_to", "not_equal_to", "greater", "less", "logical_and", "logical_or", "logical_not", "bit_and", "bit_or", "bit_xor"],
            "utility": ["pair", "move", "forward", "swap", "make_pair", "exchange", "declval", "as_const", "tuple", "get", "tuple_size", "tuple_cat", "apply"],
            "type_traits": ["is_integral", "is_floating_point", "is_arithmetic", "is_pointer", "is_reference", "is_array", "is_class", "is_enum", "is_function", "is_void", "enable_if", "conditional", "remove_const", "remove_volatile", "remove_cv", "add_const", "remove_reference", "add_lvalue_reference", "add_rvalue_reference", "remove_pointer", "add_pointer", "make_signed", "make_unsigned", "decay", "common_type", "underlying_type", "invoke_result", "is_same", "is_base_of", "is_convertible", "is_constructible", "is_assignable", "is_destructible", "is_trivially_copyable", "is_standard_layout", "is_empty", "is_polymorphic", "is_abstract", "is_final", "is_signed", "is_unsigned", "true_type", "false_type", "integral_constant"],
            "exception": ["exception", "runtime_error", "logic_error", "bad_exception", "bad_alloc", "bad_cast", "bad_typeid", "bad_function_call", "bad_weak_ptr", "terminate", "uncaught_exception", "rethrow_exception", "current_exception", "make_exception_ptr", "nested_exception", "throw_with_nested", "rethrow_if_nested"],
            "stdexcept": ["logic_error", "domain_error", "invalid_argument", "length_error", "out_of_range", "runtime_error", "range_error", "overflow_error", "underflow_error", "system_error"],
        },
        "java": {
            "java.lang": ["String", "Integer", "Double", "Boolean", "Long", "Float", "Character", "Byte", "Short", "Object", "Class", "System", "Math", "Thread", "Exception", "RuntimeException", "Error", "Throwable", "Runtime", "ClassLoader", "Package", "Void", "Number", "Comparable", "Iterable", "CharSequence", "Runnable", "ThreadLocal", "StringBuilder", "StringBuffer", "Override", "Deprecated", "SuppressWarnings", "FunctionalInterface"],
            "java.util": ["List", "ArrayList", "LinkedList", "HashMap", "HashSet", "TreeMap", "TreeSet", "LinkedHashMap", "LinkedHashSet", "Iterator", "ListIterator", "Collections", "Arrays", "Comparator", "Map", "Set", "Queue", "Deque", "PriorityQueue", "Vector", "Stack", "Hashtable", "Enumeration", "Dictionary", "Properties", "Date", "Calendar", "TimeZone", "Scanner", "Random", "UUID", "Objects", "Optional", "Formatter", "Timer", "TimerTask", "Currency", "Locale"],
            "java.io": ["File", "InputStream", "OutputStream", "FileInputStream", "FileOutputStream", "BufferedReader", "BufferedWriter", "PrintWriter", "PrintStream", "Serializable", "ObjectInputStream", "ObjectOutputStream", "Reader", "Writer", "InputStreamReader", "OutputStreamWriter", "FileReader", "FileWriter", "StringReader", "StringWriter", "ByteArrayInputStream", "ByteArrayOutputStream", "PushbackReader", "LineNumberReader", "StreamTokenizer", "DataInputStream", "DataOutputStream", "RandomAccessFile", "IOException", "FileNotFoundException", "EOFException", "Console"],
            "java.net": ["Socket", "ServerSocket", "URL", "URLConnection", "HttpURLConnection", "InetAddress", "InetSocketAddress", "DatagramSocket", "DatagramPacket", "URI", "URLEncoder", "URLDecoder", "NetworkInterface", "Proxy", "ProxySelector", "CookieHandler", "CookieManager", "HttpCookie"],
            "java.nio": ["ByteBuffer", "CharBuffer", "ShortBuffer", "IntBuffer", "LongBuffer", "FloatBuffer", "DoubleBuffer", "Path", "Paths", "Files", "FileSystem", "FileSystems", "FileStore", "ByteOrder", "MappedByteBuffer", "StandardOpenOption", "LinkOption", "CopyOption", "FileVisitOption", "FileVisitResult", "FileVisitor", "PathMatcher", "WatchService", "WatchKey", "WatchEvent"],
            "java.time": ["LocalDate", "LocalTime", "LocalDateTime", "Instant", "Duration", "Period", "ZoneId", "ZoneOffset", "ZonedDateTime", "OffsetDateTime", "OffsetTime", "Year", "YearMonth", "MonthDay", "Month", "DayOfWeek", "ChronoField", "ChronoUnit", "Clock", "DateTimeFormatter", "DateTimeFormatterBuilder", "FormatStyle", "TextStyle", "ResolverStyle", "Temporal", "TemporalAccessor", "TemporalAdjuster", "TemporalAdjusters", "TemporalAmount", "TemporalField", "TemporalQuery", "TemporalUnit", "ValueRange", "WeekFields"],
            "java.util.concurrent": ["ExecutorService", "Executors", "Future", "CompletableFuture", "CountDownLatch", "CyclicBarrier", "Semaphore", "ConcurrentHashMap", "ConcurrentLinkedQueue", "CopyOnWriteArrayList", "CopyOnWriteArraySet", "BlockingQueue", "ArrayBlockingQueue", "LinkedBlockingQueue", "PriorityBlockingQueue", "SynchronousQueue", "DelayQueue", "AtomicBoolean", "AtomicInteger", "AtomicLong", "AtomicReference", "AtomicIntegerArray", "AtomicLongArray", "AtomicReferenceArray", "ThreadFactory", "ThreadLocalRandom", "TimeUnit", "TimeoutException", "CancellationException", "ExecutionException", "InterruptedException", "RejectedExecutionException", "BrokenBarrierException", "ForkJoinPool", "ForkJoinTask", "RecursiveAction", "RecursiveTask", "Phaser", "Lock", "ReadWriteLock", "ReentrantLock", "ReentrantReadWriteLock", "StampedLock", "Condition", "LockSupport"],
            "java.util.stream": ["Stream", "IntStream", "LongStream", "DoubleStream", "Collectors", "Collector", "StreamSupport", "BaseStream"],
            "java.util.function": ["Function", "Predicate", "Consumer", "Supplier", "BiFunction", "BiPredicate", "BiConsumer", "UnaryOperator", "BinaryOperator", "IntFunction", "IntPredicate", "IntConsumer", "IntSupplier", "LongFunction", "LongPredicate", "LongConsumer", "LongSupplier", "DoubleFunction", "DoublePredicate", "DoubleConsumer", "DoubleSupplier", "ToIntFunction", "ToLongFunction", "ToDoubleFunction"],
            "java.util.regex": ["Pattern", "Matcher", "MatchResult", "PatternSyntaxException"],
            "java.util.logging": ["Logger", "Level", "LogRecord", "Handler", "ConsoleHandler", "FileHandler", "StreamHandler", "MemoryHandler", "SocketHandler", "Formatter", "SimpleFormatter", "XMLFormatter", "Filter", "ErrorManager", "LogManager"],
            "java.lang.reflect": ["Method", "Field", "Constructor", "Array", "Modifier", "Proxy", "InvocationHandler", "Member", "AccessibleObject", "ReflectPermission", "Parameter", "Executable", "GenericDeclaration", "Type", "ParameterizedType", "WildcardType", "GenericArrayType", "TypeVariable", "AnnotatedElement", "AnnotatedType", "Annotation", "Inherited", "Retention", "RetentionPolicy", "Target", "ElementType", "Documented", "Repeatable", "Native"],
            "java.security": ["MessageDigest", "SecureRandom", "KeyStore", "KeyPair", "KeyPairGenerator", "PrivateKey", "PublicKey", "Key", "Certificate", "Signature", "Cipher", "Mac", "AlgorithmParameters", "KeyFactory", "SecretKeyFactory", "KeyManager", "KeyManagerFactory", "TrustManager", "TrustManagerFactory", "SSLContext", "Policy", "Provider", "Security", "AccessController", "Permission", "Permissions", "PermissionCollection", "CodeSource", "ProtectionDomain", "Principal"],
            "java.sql": ["Connection", "Statement", "PreparedStatement", "CallableStatement", "ResultSet", "ResultSetMetaData", "DatabaseMetaData", "Driver", "DriverManager", "DriverPropertyInfo", "Date", "Time", "Timestamp", "Types", "SQLException", "SQLWarning", "BatchUpdateException", "Array", "Blob", "Clob", "NClob", "Ref", "RowId", "SQLXML", "Struct", "ParameterMetaData", "Savepoint", "DataSource", "PooledConnection", "ConnectionPoolDataSource", "XAConnection", "XADataSource"],
        },
        "ruby": {
            "base64": ["encode64", "decode64", "strict_encode64", "strict_decode64", "urlsafe_encode64", "urlsafe_decode64"],
            "json": ["parse", "generate", "load", "dump", "pretty_generate", "fast_generate", "restore"],
            "net/http": ["get", "post", "start", "new", "Get", "Post", "Put", "Delete", "Head", "Patch"],
            "set": ["Set", "add", "delete", "include", "subset", "superset", "union", "intersection", "difference", "merge", "each", "size", "empty"],
            "date": ["Date", "DateTime", "today", "parse", "jd", "civil", "ordinal", "commercial", "iso8601", "rfc3339", "httpdate"],
            "time": ["Time", "now", "at", "gm", "local", "mktime", "parse", "iso8601", "rfc3339", "httpdate"],
            "uri": ["URI", "parse", "encode", "decode", "escape", "unescape", "join", "open", "scheme", "host", "path", "query", "fragment", "port"],
            "pathname": ["Pathname", "new", "getwd", "pwd", "glob", "join", "parent", "dirname", "basename", "extname", "open", "read", "write", "exist", "directory", "file", "mkpath", "rmtree", "mkdir", "rmdir", "delete", "rename", "expand_path", "realpath", "cleanpath", "ascend", "descend", "root"],
            "fileutils": ["cp", "mv", "rm", "mkdir_p", "mkdir", "rmdir", "ln_s", "ln_sf", "cp_r", "rm_r", "rm_rf", "chmod", "chown", "touch", "copy_file", "copy_entry", "copy_stream", "compare_file", "uptodate", "cd", "pwd", "chdir", "getwd", "install"],
            "logger": ["Logger", "new", "info", "warn", "error", "debug", "fatal", "unknown", "log", "add", "close", "reopen", "level", "datetime_format", "progname", "formatter", "severity", "logdev"],
            "csv": ["CSV", "parse", "generate", "read", "readlines", "foreach", "open", "filter", "table", "Row", "Table"],
            "yaml": ["YAML", "load", "load_file", "dump", "dump_file", "parse", "parse_file", "dump_stream", "load_stream", "load_documents", "dump_documents", "parse_stream", "emit", "emit_file", "emit_stream", "to_yaml"],
            "digest": ["Digest", "SHA256", "SHA1", "MD5", "SHA512", "SHA384", "SHA224", "RMD160", "hexencode", "hexdecode"],
            "securerandom": ["SecureRandom", "random_bytes", "hex", "base64", "urlsafe_base64", "uuid", "random_number", "random_integer", "alphanumeric"],
            "erb": ["ERB", "new", "result", "run", "src", "def_method", "def_module", "def_class", "set_eoutvar", "version"],
            "optparse": ["OptionParser", "new", "parse", "parse!", "on", "banner", "program_name", "version", "release", "summarize", "help", "to_a", "accept", "reject", "complete", "environment", "load"],
            "tempfile": ["Tempfile", "new", "open", "create", "close", "close!", "unlink", "delete", "path", "length", "size", "flock", "flush", "pos", "lineno", "rewind", "seek", "eof", "gets", "puts", "read", "write", "binmode"],
            "benchmark": ["Benchmark", "measure", "realtime", "benchmark", "bm", "bmbm", "report", "Tms", "real", "utime", "stime", "cutime", "cstime", "total", "label"],
            "singleton": ["Singleton", "instance", "clone", "dup", "new", "included", "append_features"],
            "monitor": ["Monitor", "MonitorMixin", "new", "synchronize", "mon_synchronize", "mon_enter", "mon_exit", "mon_try_enter", "new_cond", "wait_for", "wait_while", "wait_until", "signal", "broadcast", "timedwait"],
        },
        "csharp": {
            "System": ["String", "Int32", "Double", "Boolean", "Object", "Array", "Math", "Convert", "Console", "Environment", "Byte", "Char", "Decimal", "Single", "Int64", "Int16", "SByte", "UInt16", "UInt32", "UInt64", "DateTime", "TimeSpan", "Guid", "Type", "Enum", "Nullable", "Tuple", "ValueTuple", "Action", "Func", "Predicate", "Comparison", "Converter", "EventHandler", "EventArgs", "Exception", "InvalidOperationException", "ArgumentException", "ArgumentNullException", "ArgumentOutOfRangeException", "NotImplementedException", "NotSupportedException", "NullReferenceException", "IndexOutOfRangeException", "FormatException", "OverflowException", "TimeoutException", "GC", "AppDomain", "Uri", "Version", "Random", "BitConverter", "Buffer", "Span", "ReadOnlySpan", "Memory", "ReadOnlyMemory"],
            "System.Collections": ["ArrayList", "Hashtable", "Stack", "Queue", "SortedList", "BitArray", "Comparer", "CaseInsensitiveComparer", "DictionaryEntry", "ICollection", "IComparer", "IDictionary", "IDictionaryEnumerator", "IEnumerable", "IEnumerator", "IEqualityComparer", "IList", "IStructuralComparable", "IStructuralEquatable"],
            "System.Collections.Generic": ["List", "Dictionary", "HashSet", "LinkedList", "Queue", "Stack", "SortedList", "SortedDictionary", "SortedSet", "KeyNotFoundException", "KeyValuePair", "ICollection", "IComparer", "IDictionary", "IEnumerable", "IEnumerator", "IEqualityComparer", "IList", "IReadOnlyCollection", "IReadOnlyDictionary", "IReadOnlyList", "ISet", "EqualityComparer", "Comparer"],
            "System.IO": ["File", "Directory", "Path", "StreamReader", "StreamWriter", "FileStream", "MemoryStream", "BinaryReader", "BinaryWriter", "StringReader", "StringWriter", "TextReader", "TextWriter", "BufferedStream", "DirectoryInfo", "FileInfo", "FileSystemInfo", "FileSystemWatcher", "IOException", "FileNotFoundException", "DirectoryNotFoundException", "DriveInfo", "FileMode", "FileAccess", "FileShare", "FileOptions", "FileAttributes", "NotifyFilters", "WatcherChangeTypes", "SeekOrigin"],
            "System.Net": ["HttpClient", "WebClient", "HttpWebRequest", "HttpWebResponse", "IPAddress", "Dns", "IPEndPoint", "EndPoint", "WebHeaderCollection", "NetworkCredential", "CredentialCache", "Cookie", "CookieCollection", "CookieContainer", "HttpListener", "Socket", "TcpClient", "TcpListener", "UdpClient", "NetworkStream", "WebProxy", "WebException"],
            "System.Net.Http": ["HttpClient", "HttpRequestMessage", "HttpResponseMessage", "HttpContent", "StringContent", "ByteArrayContent", "StreamContent", "FormUrlEncodedContent", "MultipartContent", "MultipartFormDataContent", "HttpMethod", "HttpClientHandler", "DelegatingHandler"],
            "System.Threading": ["Thread", "Mutex", "Semaphore", "Monitor", "Interlocked", "CancellationToken", "CancellationTokenSource", "WaitHandle", "AutoResetEvent", "ManualResetEvent", "ManualResetEventSlim", "CountdownEvent", "Barrier", "SpinWait", "SpinLock", "ReaderWriterLock", "ReaderWriterLockSlim", "ThreadStart", "ParameterizedThreadStart", "ThreadState", "ThreadPriority", "ThreadPool", "Timer", "TimerCallback", "Timeout", "Volatile", "Lazy", "AsyncLocal"],
            "System.Threading.Tasks": ["Task", "TaskFactory", "TaskScheduler", "TaskContinuationOptions", "TaskCreationOptions", "TaskStatus", "TaskCanceledException", "TaskCompletionSource", "ValueTask"],
            "System.Linq": ["Enumerable", "Queryable", "IGrouping", "ILookup", "IOrderedEnumerable", "IOrderedQueryable", "Lookup"],
            "System.Text": ["StringBuilder", "Encoding", "UTF8Encoding", "UnicodeEncoding", "UTF32Encoding", "ASCIIEncoding", "Decoder", "Encoder", "Rune", "NormalizationForm"],
            "System.Text.RegularExpressions": ["Regex", "Match", "Group", "Capture", "MatchCollection", "GroupCollection", "CaptureCollection", "RegexOptions", "RegexMatchTimeoutException"],
            "System.Reflection": ["Assembly", "Type", "MethodInfo", "FieldInfo", "PropertyInfo", "ConstructorInfo", "EventInfo", "ParameterInfo", "MemberInfo", "MethodBase", "BindingFlags", "MemberTypes", "TypeAttributes", "MethodAttributes", "FieldAttributes", "CustomAttributeData", "TypeInfo", "AssemblyName", "AmbiguousMatchException", "TargetException", "TargetInvocationException", "TargetParameterCountException"],
            "System.Diagnostics": ["Debug", "Trace", "TraceSource", "TraceListener", "TextWriterTraceListener", "ConsoleTraceListener", "EventLogTraceListener", "XmlWriterTraceListener", "TraceSwitch", "BooleanSwitch", "TraceLevel", "Stopwatch", "Process", "ProcessModule", "ProcessThread", "ProcessStartInfo", "Debugger", "StackFrame", "StackTrace", "ConditionalAttribute", "EventLog", "PerformanceCounter"],
            "System.Globalization": ["CultureInfo", "DateTimeFormatInfo", "NumberFormatInfo", "Calendar", "GregorianCalendar", "CompareInfo", "SortKey", "RegionInfo", "TextInfo", "StringInfo", "UnicodeCategory", "NumberStyles", "DateTimeStyles", "CultureTypes", "CalendarWeekRule", "CalendarAlgorithmType"],
            "System.Security": ["MD5", "SHA1", "SHA256", "SHA384", "SHA512", "CryptoStream", "HashAlgorithm", "KeyedHashAlgorithm", "HMAC", "HMACMD5", "HMACSHA1", "HMACSHA256", "HMACSHA384", "HMACSHA512", "RandomNumberGenerator", "RSA", "DSA", "AsymmetricAlgorithm", "SymmetricAlgorithm", "Aes", "DES", "TripleDES", "RC2", "Rijndael", "ICryptoTransform", "X509Certificate", "X509Certificate2", "X509Chain", "X509Store", "StoreLocation", "StoreName", "OpenFlags"],
        },
        "php": {
            "spl": ["SplDoublyLinkedList", "SplStack", "SplQueue", "SplHeap", "SplMinHeap", "SplMaxHeap", "SplPriorityQueue", "SplFixedArray", "SplObjectStorage", "ArrayObject", "ArrayIterator", "RecursiveArrayIterator", "SplFileInfo", "SplFileObject", "SplTempFileObject", "DirectoryIterator", "RecursiveDirectoryIterator", "FilesystemIterator", "GlobIterator", "CallbackFilterIterator", "RecursiveCallbackFilterIterator", "EmptyIterator", "InfiniteIterator", "LimitIterator", "NoRewindIterator", "AppendIterator", "CachingIterator", "RegexIterator", "RecursiveRegexIterator"],
            "pdo": ["PDO", "PDOStatement", "PDOException", "ATTR_DRIVER_NAME", "ATTR_ERRMODE", "ERRMODE_SILENT", "ERRMODE_WARNING", "ERRMODE_EXCEPTION", "ATTR_SERVER_VERSION", "ATTR_AUTOCOMMIT", "ATTR_DEFAULT_FETCH_MODE", "FETCH_ASSOC", "FETCH_NUM", "FETCH_BOTH", "FETCH_OBJ", "FETCH_LAZY", "FETCH_BOUND", "FETCH_COLUMN", "FETCH_CLASS", "FETCH_INTO", "FETCH_FUNC", "FETCH_NAMED", "FETCH_KEY_PAIR", "FETCH_GROUP", "FETCH_UNIQUE"],
            "datetime": ["DateTime", "DateTimeImmutable", "DateTimeInterface", "DateTimeZone", "DateInterval", "DatePeriod", "createFromFormat", "getLastErrors", "getTimezone", "setTimezone", "getOffset", "add", "sub", "diff", "format", "getTimestamp", "setTimestamp", "setDate", "setTime", "modify"],
            "json": ["json_encode", "json_decode", "json_last_error", "json_last_error_msg", "json_validate", "JSON_PRETTY_PRINT", "JSON_UNESCAPED_SLASHES", "JSON_UNESCAPED_UNICODE", "JSON_THROW_ON_ERROR", "JSON_FORCE_OBJECT", "JSON_NUMERIC_CHECK", "JSON_BIGINT_AS_STRING", "JSON_PRESERVE_ZERO_FRACTION"],
            "mbstring": ["mb_strlen", "mb_substr", "mb_strpos", "mb_strrpos", "mb_strtolower", "mb_strtoupper", "mb_convert_case", "mb_convert_encoding", "mb_detect_encoding", "mb_detect_order", "mb_internal_encoding", "mb_split", "mb_ereg", "mb_eregi", "mb_ereg_replace", "mb_eregi_replace", "mb_ereg_match", "mb_check_encoding", "mb_ord", "mb_chr", "mb_str_split", "mb_strstr", "mb_stristr", "mb_strrchr", "mb_substr_count", "mb_strcut", "mb_strimwidth", "mb_str_pad", "mb_trim", "mb_ltrim", "mb_rtrim"],
            "ctype": ["ctype_alpha", "ctype_digit", "ctype_alnum", "ctype_xdigit", "ctype_punct", "ctype_space", "ctype_upper", "ctype_lower", "ctype_print", "ctype_graph", "ctype_cntrl"],
            "filter": ["filter_var", "filter_input", "filter_list", "filter_id", "filter_has_var", "filter_var_array", "filter_input_array", "FILTER_VALIDATE_INT", "FILTER_VALIDATE_FLOAT", "FILTER_VALIDATE_BOOL", "FILTER_VALIDATE_REGEXP", "FILTER_VALIDATE_URL", "FILTER_VALIDATE_EMAIL", "FILTER_VALIDATE_IP", "FILTER_VALIDATE_MAC", "FILTER_DEFAULT", "FILTER_UNSAFE_RAW", "FILTER_SANITIZE_STRING", "FILTER_SANITIZE_ENCODED", "FILTER_SANITIZE_EMAIL", "FILTER_SANITIZE_URL", "FILTER_SANITIZE_NUMBER_INT", "FILTER_SANITIZE_NUMBER_FLOAT", "FILTER_REQUIRE_SCALAR", "FILTER_REQUIRE_ARRAY", "FILTER_NULL_ON_FAILURE", "INPUT_GET", "INPUT_POST", "INPUT_COOKIE", "INPUT_SERVER", "INPUT_ENV"],
            "hash": ["hash", "hash_file", "hash_hmac", "hash_hmac_file", "hash_init", "hash_update", "hash_final", "hash_copy", "hash_algos", "hash_hmac_algos", "hash_pbkdf2", "hash_equals", "hash_hkdf", "HASH_MD5", "HASH_SHA1", "HASH_SHA224", "HASH_SHA256", "HASH_SHA384", "HASH_SHA512", "HASH_CRC32", "HASH_ADLER32"],
            "openssl": ["openssl_encrypt", "openssl_decrypt", "openssl_cipher_iv_length", "openssl_digest", "openssl_get_cipher_methods", "openssl_get_md_methods", "openssl_pbkdf2", "openssl_random_pseudo_bytes", "openssl_error_string", "openssl_open", "openssl_seal", "openssl_sign", "openssl_verify", "openssl_private_encrypt", "openssl_private_decrypt", "openssl_public_encrypt", "openssl_public_decrypt", "openssl_pkey_new", "openssl_pkey_free", "openssl_pkey_export", "openssl_pkey_get_private", "openssl_pkey_get_public", "openssl_pkey_get_details", "openssl_csr_new", "openssl_csr_export", "openssl_csr_sign", "openssl_x509_read", "openssl_x509_parse", "openssl_x509_check_private_key", "openssl_x509_checkpurpose", "openssl_x509_export", "openssl_x509_fingerprint", "openssl_pkcs12_export", "openssl_pkcs12_read", "OPENSSL_RAW_DATA", "OPENSSL_KEYTYPE_RSA", "OPENSSL_KEYTYPE_DSA", "OPENSSL_KEYTYPE_EC", "OPENSSL_ALGO_MD5", "OPENSSL_ALGO_SHA1", "OPENSSL_ALGO_SHA256", "OPENSSL_ALGO_SHA512"],
            "curl": ["curl_init", "curl_exec", "curl_close", "curl_setopt", "curl_setopt_array", "curl_getinfo", "curl_error", "curl_errno", "curl_reset", "curl_copy_handle", "curl_pause", "curl_escape", "curl_unescape", "curl_multi_init", "curl_multi_add_handle", "curl_multi_remove_handle", "curl_multi_exec", "curl_multi_select", "curl_multi_info_read", "curl_multi_close", "curl_share_init", "curl_share_close", "curl_share_setopt", "CURLOPT_URL", "CURLOPT_RETURNTRANSFER", "CURLOPT_POST", "CURLOPT_POSTFIELDS", "CURLOPT_HTTPHEADER", "CURLOPT_CUSTOMREQUEST", "CURLOPT_TIMEOUT", "CURLOPT_CONNECTTIMEOUT", "CURLOPT_FOLLOWLOCATION", "CURLOPT_SSL_VERIFYPEER", "CURLOPT_SSL_VERIFYHOST", "CURLOPT_USERAGENT", "CURLOPT_HEADER", "CURLOPT_NOBODY", "CURLOPT_ENCODING", "CURLOPT_REFERER", "CURLOPT_COOKIE", "CURLOPT_COOKIEFILE", "CURLOPT_COOKIEJAR", "CURLOPT_PROXY", "CURLOPT_HTTPAUTH", "CURLOPT_USERPWD", "CURLOPT_FILE", "CURLOPT_WRITEFUNCTION", "CURLOPT_READFUNCTION", "CURLOPT_HEADERFUNCTION", "CURLOPT_VERBOSE", "CURLOPT_FAILONERROR"],
            "sockets": ["socket_create", "socket_connect", "socket_bind", "socket_listen", "socket_accept", "socket_read", "socket_write", "socket_close", "socket_recv", "socket_send", "socket_recvfrom", "socket_sendto", "socket_set_block", "socket_set_nonblock", "socket_set_option", "socket_get_option", "socket_getpeername", "socket_getsockname", "socket_create_pair", "socket_shutdown", "socket_strerror", "socket_last_error", "socket_clear_error", "socket_select", "SOCK_STREAM", "SOCK_DGRAM", "SOCK_RAW", "AF_INET", "AF_INET6", "AF_UNIX", "SOL_SOCKET", "SO_REUSEADDR", "SO_KEEPALIVE", "SO_LINGER", "SO_BROADCAST", "SO_RCVBUF", "SO_SNDBUF", "TCP_NODELAY", "MSG_OOB", "MSG_PEEK", "MSG_WAITALL", "MSG_DONTWAIT"],
            "reflection": ["ReflectionClass", "ReflectionMethod", "ReflectionFunction", "ReflectionProperty", "ReflectionParameter", "ReflectionExtension", "ReflectionObject", "ReflectionException", "ReflectionType", "ReflectionNamedType", "ReflectionUnionType", "ReflectionIntersectionType", "ReflectionEnum", "ReflectionEnumUnitCase", "ReflectionEnumBackedCase", "ReflectionFiber", "ReflectionAttribute", "ReflectionReference", "ReflectionClassConstant", "ReflectionGenerator"],
            "dom": ["DOMDocument", "DOMElement", "DOMNode", "DOMNodeList", "DOMNamedNodeMap", "DOMAttr", "DOMText", "DOMCdataSection", "DOMComment", "DOMDocumentFragment", "DOMDocumentType", "DOMNotation", "DOMEntity", "DOMEntityReference", "DOMProcessingInstruction", "DOMCharacterData", "DOMException", "DOMImplementation", "DOMXPath"],
            "simplexml": ["SimpleXMLElement", "SimpleXMLIterator", "simplexml_load_file", "simplexml_load_string", "simplexml_import_dom", "asXML", "saveXML", "addChild", "addAttribute", "attributes", "children", "count", "getName", "getNamespaces", "getDocNamespaces", "registerXPathNamespace", "xpath"],
            "xml": ["xml_parser_create", "xml_parser_create_ns", "xml_parser_free", "xml_parser_set_option", "xml_parser_get_option", "xml_set_element_handler", "xml_set_character_data_handler", "xml_set_processing_instruction_handler", "xml_set_notation_decl_handler", "xml_set_unparsed_entity_decl_handler", "xml_set_external_entity_ref_handler", "xml_set_start_namespace_decl_handler", "xml_set_end_namespace_decl_handler", "xml_parse", "xml_parse_into_struct", "xml_get_error_code", "xml_error_string", "xml_get_current_line_number", "xml_get_current_column_number", "xml_get_current_byte_index", "XML_OPTION_CASE_FOLDING", "XML_OPTION_SKIP_TAGSTART", "XML_OPTION_SKIP_WHITE", "XML_OPTION_TARGET_ENCODING", "XML_ERROR_NONE", "XML_ERROR_SYNTAX", "XML_ERROR_INVALID_TOKEN", "XML_ERROR_TAG_MISMATCH", "XML_ERROR_DUPLICATE_ATTRIBUTE", "XML_ERROR_JUNK_AFTER_DOC_ELEMENT", "XML_ERROR_UNDEFINED_ENTITY", "XML_ERROR_UNCLOSED_TOKEN", "XML_ERROR_PARTIAL_CHAR"],
            "zlib": ["gzopen", "gzread", "gzwrite", "gzclose", "gzeof", "gzgets", "gzgetc", "gzgetss", "gzputs", "gzrewind", "gzseek", "gztell", "gzcompress", "gzuncompress", "gzdeflate", "gzinflate", "gzencode", "gzdecode", "gzfile", "readgzfile", "zlib_decode", "zlib_encode", "ob_gzhandler", "ZLIB_ENCODING_RAW", "ZLIB_ENCODING_GZIP", "ZLIB_ENCODING_DEFLATE", "ZLIB_NO_FLUSH", "ZLIB_PARTIAL_FLUSH", "ZLIB_SYNC_FLUSH", "ZLIB_FULL_FLUSH", "ZLIB_FINISH", "ZLIB_FILTERED", "ZLIB_HUFFMAN_ONLY", "ZLIB_RLE", "ZLIB_FIXED", "ZLIB_DEFAULT_STRATEGY", "ZLIB_VERSION", "ZLIB_OK", "ZLIB_STREAM_END", "ZLIB_NEED_DICT", "ZLIB_ERRNO", "ZLIB_STREAM_ERROR", "ZLIB_DATA_ERROR", "ZLIB_MEM_ERROR", "ZLIB_BUF_ERROR"],
            "fileinfo": ["finfo_open", "finfo_close", "finfo_set_flags", "finfo_file", "finfo_buffer", "mime_content_type", "FILEINFO_NONE", "FILEINFO_SYMLINK", "FILEINFO_MIME_TYPE", "FILEINFO_MIME_ENCODING", "FILEINFO_MIME", "FILEINFO_EXTENSION", "FILEINFO_RAW", "FILEINFO_PRESERVE_CASE", "FILEINFO_DEVICES", "FILEINFO_CONTINUE", "FILEINFO_NO_CHECK", "FILEINFO_APPLE"],
            "intl": ["Intl", "NumberFormatter", "MessageFormatter", "Locale", "Collator", "DateFormatter", "Normalizer", "ResourceBundle", "Transliterator", "IntlChar", "IntlCalendar", "IntlGregorianCalendar", "IntlBreakIterator", "IntlRuleBasedBreakIterator", "IntlCodePointBreakIterator", "IntlException", "Spoofchecker"],
        },
        "kotlin": {
            "kotlin.collections": ["List", "Set", "Map", "MutableList", "listOf"],
            "kotlin.io": ["File", "print", "println", "readLine", "readText"],
            "kotlin.math": ["abs", "sqrt", "ceil", "floor", "round"],
            "kotlin.text": ["String", "StringBuilder", "Regex", "trim", "split"],
            "kotlin.ranges": ["IntRange", "until", "downTo", "step", "rangeTo"],
            "kotlin.sequences": ["Sequence", "generateSequence", "map", "filter", "toList"],
            "kotlin.concurrent": ["Volatile", "Thread", "Mutex", "launch", "async"],
            "kotlin.reflect": ["KClass", "KCallable", "KProperty", "KFunction", "KType"],
            "kotlin.system": ["exitProcess", "measureTimeMillis", "currentTimeMillis", "nanoTime"],
            "kotlin.time": ["Duration", "DurationUnit", "measureTime", "TimeSource"],
            "kotlin.random": ["Random", "nextInt", "nextLong", "nextBoolean", "nextBytes"],
            "kotlin.properties": ["ReadOnlyProperty", "ReadWriteProperty", "Delegates", "observable", "notNull"],
        },
        "swift": {
            "Foundation": ["NSObject", "NSArray", "NSDictionary", "NSString", "NSData"],
            "Swift": ["Array", "Dictionary", "Set", "String", "Optional"],
            "Dispatch": ["DispatchQueue", "DispatchGroup", "DispatchSemaphore", "DispatchWorkItem"],
            "Combine": ["Publisher", "Subscriber", "Cancellable", "AnyPublisher", "Future"],
            "CryptoKit": ["SHA256", "SHA512", "SymmetricKey", "AES", "ChaChaPoly"],
            "XCTest": ["XCTestCase", "XCTest", "XCTestSuite", "XCTestExpectation", "XCTContext"],
        },
        "scala": {
            "scala.collection": ["Seq", "List", "Vector", "Map", "Set"],
            "scala.collection.immutable": ["List", "Vector", "Map", "Set", "Queue"],
            "scala.collection.mutable": ["ArrayBuffer", "ListBuffer", "HashMap", "HashSet", "Builder"],
            "scala.concurrent": ["Future", "Promise", "Await", "ExecutionContext", "Duration"],
            "scala.io": ["Source", "BufferedSource", "Codec", "StdIn", "StdOut"],
            "scala.math": ["abs", "max", "min", "sqrt", "pow"],
            "scala.util": ["Try", "Success", "Failure", "Either", "Random"],
            "scala.util.matching": ["Regex", "Match", "MatchData", "MatchIterator"],
            "scala.reflect": ["ClassTag", "TypeTag", "Universe", "Mirror", "Type"],
            "scala.sys": ["System", "Prop", "BooleanProp", "SystemProperties"],
            "scala.runtime": ["ScalaRunTime", "BoxesRunTime", "RichInt", "RichString", "RichArray"],
        },
        "dart": {
            "dart:core": ["List", "Set", "Map", "String", "int"],
            "dart:async": ["Future", "Stream", "StreamController", "Completer", "Timer"],
            "dart:collection": ["HashMap", "LinkedHashMap", "HashSet", "Queue", "SplayTreeMap"],
            "dart:convert": ["jsonEncode", "jsonDecode", "JsonCodec", "Utf8Codec", "Base64Codec"],
            "dart:io": ["File", "Directory", "HttpClient", "HttpServer", "Process"],
            "dart:math": ["Random", "sqrt", "pow", "sin", "cos"],
            "dart:typed_data": ["ByteData", "Uint8List", "Int32List", "Float64List", "Endianness"],
            "dart:isolate": ["Isolate", "ReceivePort", "SendPort", "RawReceivePort"],
        },
        "haskell": {
            "Prelude": ["map", "filter", "foldr", "head", "tail"],
            "Data.List": ["sort", "nub", "partition", "find", "intersperse"],
            "Data.Maybe": ["maybe", "isJust", "isNothing", "fromJust", "fromMaybe"],
            "Data.Either": ["either", "lefts", "rights", "isLeft", "isRight"],
            "Data.Char": ["isAlpha", "isDigit", "toUpper", "toLower", "ord"],
            "Data.Map": ["Map", "empty", "insert", "delete", "lookup"],
            "Data.Set": ["Set", "empty", "insert", "delete", "member"],
            "Data.IORef": ["IORef", "newIORef", "readIORef", "writeIORef", "modifyIORef"],
            "Data.Array": ["Array", "listArray", "array", "elems", "bounds"],
            "Data.ByteString": ["ByteString", "pack", "unpack", "concat", "foldl"],
            "Data.Text": ["Text", "pack", "unpack", "concat", "map"],
            "System.IO": ["IO", "Handle", "readFile", "writeFile", "putStrLn"],
            "Control.Monad": ["mapM", "sequence", "when", "unless", "forever"],
        },
        "lua": {
            "base": ["print", "type", "tostring", "tonumber", "error"],
            "string": ["find", "format", "gsub", "len", "match"],
            "table": ["concat", "insert", "remove", "sort", "pack"],
            "math": ["abs", "ceil", "floor", "max", "min"],
            "io": ["open", "read", "write", "close", "lines"],
            "os": ["time", "date", "clock", "exit", "getenv"],
            "coroutine": ["create", "resume", "yield", "status", "wrap"],
            "debug": ["getinfo", "getlocal", "sethook", "traceback", "getmetatable"],
            "package": ["loaded", "loadlib", "path", "searchpath", "seeall"],
        },
        "r": {
            "base": ["print", "c", "list", "length", "mean"],
            "stats": ["lm", "glm", "t.test", "cor", "var"],
            "utils": ["read.csv", "write.csv", "head", "tail", "str"],
            "graphics": ["plot", "points", "lines", "abline", "legend"],
            "grDevices": ["dev.new", "dev.off", "pdf", "png", "rainbow"],
            "datasets": ["mtcars", "iris", "airquality", "ChickWeight", "CO2"],
            "methods": ["setClass", "setMethod", "new", "show", "is"],
        },
        "perl": {
            "strict": ["strict", "vars", "subs", "refs"],
            "warnings": ["warnings", "FATAL", "all", "uninitialized"],
            "Carp": ["croak", "carp", "confess", "cluck", "verbose"],
            "Data::Dumper": ["Dumper", "Dump", "Sortkeys", "Indent", "Terse"],
            "File::Spec": ["catfile", "catdir", "splitpath", "canonpath", "tmpdir"],
            "File::Basename": ["fileparse", "basename", "dirname", "fileparse_set_fstype"],
            "File::Path": ["make_path", "remove_tree", "mkpath", "rmtree"],
            "Getopt::Long": ["GetOptions", "Configure", "HelpMessage", "VersionMessage"],
            "IO::File": ["new", "open", "close", "getline", "print"],
            "IO::Socket": ["new", "accept", "connect", "bind", "listen"],
            "JSON": ["encode_json", "decode_json", "from_json", "to_json", "true"],
            "List::Util": ["first", "max", "min", "sum", "reduce"],
            "Scalar::Util": ["blessed", "reftype", "weaken", "looks_like_number", "openhandle"],
            "Encode": ["encode", "decode", "encode_utf8", "decode_utf8", "find_encoding"],
            "POSIX": ["strftime", "ceil", "floor", "exit", "fork"],
        },
        "julia": {
            "Base": ["print", "println", "length", "size", "push!"],
            "Collections": ["Dict", "Set", "SortedDict", "SortedSet", "deque"],
            "LinearAlgebra": ["Matrix", "Vector", "dot", "cross", "norm"],
            "Statistics": ["mean", "std", "var", "median", "quantile"],
            "Random": ["rand", "randn", "randstring", "seed!", "MersenneTwister"],
            "Dates": ["DateTime", "Date", "Time", "now", "DateTime"],
            "Printf": ["@printf", "@sprintf", "format", "printf", "sprintf"],
            "Logging": ["@info", "@warn", "@error", "@debug", "Logging"],
            "Test": ["@test", "@testset", "@test_throws", "@test_skip", "@test_broken"],
            "Serialization": ["serialize", "deserialize"],
            "Sockets": ["connect", "listen", "accept", "send", "recv"],
            "Markdown": ["@doc_str", "markdown", "html", "latex", "term"],
        },
        "zig": {
            "std": ["debug", "fmt", "mem", "io", "fs"],
            "std.mem": ["Allocator", "allocate", "free", "copy", "set"],
            "std.fmt": ["format", "print", "scan", "bufPrint", "allocPrint"],
            "std.io": ["Reader", "Writer", "getStdIn", "getStdOut", "getStdErr"],
            "std.fs": ["File", "Dir", "cwd", "openFile", "createFile"],
            "std.debug": ["print", "assert", "panic", "dump"],
            "std.math": ["sqrt", "sin", "cos", "tan", "abs"],
            "std.time": ["nanoTimestamp", "milliTimestamp", "sleep", "timer", "Timer"],
            "std.rand": ["Random", "init", "int", "boolean", "fill"],
            "std.json": ["parse", "stringify", "Value", "Parser", "stringify"],
            "std.process": ["args", "getEnvVar", "exit", "ArgsAllocator"],
            "std.thread": ["Thread", "spawn", "join", "Mutex", "Condition"],
        },
        "bash": {
            "coreutils": ["echo", "printf", "read", "test", "printf"],
            "fileutils": ["cat", "cp", "mv", "rm", "mkdir"],
            "textutils": ["grep", "sed", "awk", "cut", "tr"],
            "findutils": ["find", "locate", "xargs", "updatedb"],
            "shell_builtins": ["cd", "pwd", "export", "source", "alias"],
            "conditional": ["if", "then", "else", "elif", "fi"],
            "loop": ["for", "while", "until", "do", "done"],
            "variables": ["$?", "$!", "$$", "$0", "$#"],
            "string_ops": ["${var:-default}", "${var%%pattern}", "${var//old/new}", "${#var}", "${var:offset:length}"],
            "io_redir": [">", ">>", "<", "2>", "2>&1"],
            "signals": ["trap", "kill", "wait", "SIGINT", "SIGTERM"],
            "arrays": ["declare", "read", "mapfile", "compgen", "complete"],
        },
        "objc": {
            "Foundation": ["NSObject", "NSString", "NSArray", "NSDictionary", "NSData"],
            "UIKit": ["UIView", "UIViewController", "UILabel", "UIButton", "UIScreen"],
            "CoreFoundation": ["CFString", "CFArray", "CFDictionary", "CFNumber", "CFData"],
            "CoreGraphics": ["CGContext", "CGPath", "CGImage", "CGColor", "CGRect"],
            "CoreAnimation": ["CALayer", "CAAnimation", "CABasicAnimation", "CAKeyframeAnimation", "CATransaction"],
            "CoreData": ["NSManagedObject", "NSManagedObjectContext", "NSManagedObjectModel", "NSPersistentStoreCoordinator", "NSEntityDescription"],
            "Dispatch": ["dispatch_queue_t", "dispatch_async", "dispatch_sync", "dispatch_group_t", "dispatch_semaphore_t"],
            "Security": ["SecKey", "SecCertificate", "SecTrust", "SecIdentity", "SecAccessControl"],
            "Accounts": ["ACAccount", "ACAccountStore", "ACAccountType", "ACAccountCredential"],
            "AddressBook": ["ABAddressBook", "ABPerson", "ABRecord", "ABMultiValue", "ABGroup"],
            "AudioToolbox": ["AudioQueue", "AudioConverter", "AudioFile", "AudioServices", "SystemSoundID"],
            "AVFoundation": ["AVPlayer", "AVAsset", "AVAudioPlayer", "AVCaptureSession", "AVAudioRecorder"],
        },
        "erlang": {
            "erlang": ["spawn", "send", "receive", "self", "link"],
            "lists": ["map", "filter", "foldl", "foldr", "reverse"],
            "dict": ["new", "store", "fetch", "erase", "to_list"],
            "sets": ["new", "add_element", "del_element", "is_element", "union"],
            "io": ["format", "fwrite", "put_chars", "get_line", "nl"],
            "file": ["open", "close", "read", "write", "consult"],
            "os": ["getenv", "putenv", "system_time", "timestamp", "cmd"],
            "timer": ["send_after", "send_interval", "apply_after", "apply_interval", "sleep"],
            "gen_server": ["start", "start_link", "call", "cast", "stop"],
            "gen_fsm": ["start", "start_link", "send_event", "send_all_state_event", "sync_send_event"],
            "supervisor": ["start_link", "start_child", "terminate_child", "delete_child", "which_children"],
            "application": ["start", "stop", "load", "unload", "get_env"],
            "crypto": ["hash", "hmac", "encrypt", "decrypt", "strong_rand_bytes"],
            "ssl": ["connect", "listen", "accept", "close", "send"],
            "re": ["compile", "run", "replace", "split", "grep"],
            "json": ["encode", "decode", "encode_to_binary", "decode_from_binary"],
            "mnesia": ["create_table", "write", "read", "delete", "transaction"],
            "ets": ["new", "insert", "lookup", "delete", "tab2list"],
            "dets": ["open_file", "insert", "lookup", "delete", "close"],
        },
        "ocaml": {
            "Stdlib": ["print_endline", "read_line", "string_of_int", "int_of_string", "float_of_int"],
            "List": ["map", "filter", "fold_left", "fold_right", "length"],
            "Array": ["make", "get", "set", "length", "to_list"],
            "String": ["length", "get", "set", "sub", "concat"],
            "Hashtbl": ["create", "add", "find", "remove", "length"],
            "Map": ["empty", "add", "find", "remove", "bindings"],
            "Set": ["empty", "add", "mem", "remove", "elements"],
            "Buffer": ["create", "add_char", "add_string", "contents", "clear"],
            "Printf": ["printf", "fprintf", "sprintf", "eprintf", "fprintf"],
            "Scanf": ["scanf", "fscanf", "sscanf", "sscanf"],
            "Sys": ["argv", "exit", "getenv", "setenv", "time"],
            "Unix": ["openfile", "close", "read", "write", "fork"],
            "Str": ["regexp", "string_match", "search_forward", "replace", "split"],
            "Digest": ["string", "file", "to_hex", "from_hex"],
            "Random": ["init", "full_init", "int", "float", "bits"],
            "Filename": ["temp_file", "concat", "dirname", "basename", "extension"],
            "Format": ["printf", "fprintf", "asprintf", "str_formatter"],
            "Bytes": ["make", "get", "set", "sub", "concat"],
            "Queue": ["create", "push", "pop", "peek", "length"],
            "Stack": ["create", "push", "pop", "top", "length"],
        },
        "hack": {
            "HH.Lib": ["vec", "dict", "keyset", "Vec\\map", "Vec\\filter"],
            "HH.Lib.C": ["compare", "less", "greater", "less_equal", "greater_equal"],
            "HH.Lib.Dict": ["map", "filter", "keys", "values", "merge"],
            "HH.Lib.Vec": ["map", "filter", "reduce", "reverse", "sort"],
            "HH.Lib.Keyset": ["map", "filter", "union", "intersect", "diff"],
            "HH.Lib.Math": ["abs", "max", "min", "sqrt", "round"],
            "HH.Lib.Str": ["length", "contains", "replace", "split", "trim"],
            "HH.Lib.File": ["read", "write", "exists", "mkdir", "remove"],
            "HH.Lib.Network": ["curl_init", "curl_exec", "curl_close"],
            "HH.Lib.Async": ["async", "await", "Awaitable", "sleep", "usleep"],
            "HH.Lib.DateTime": ["now", "format", "diff", "modify", "getTimestamp"],
            "HH.Lib.JSON": ["encode", "decode", "encode_shape", "decode_shape"],
            "HH.Lib.Regex": ["match", "replace", "split", "capture"],
            "HH.Lib.Experimental": ["Vec\\flat_map", "Dict\\flat_map", "Vec\\chunk", "Vec\\zip"],
            "HH.Lib.Unicode": ["tolower", "toupper", "length", "substr"],
        },
        "verilog": {
            "std": ["logic", "wire", "reg", "assign", "always"],
            "std.uvm": ["uvm_component", "uvm_test", "uvm_env", "uvm_agent", "uvm_scoreboard"],
            "std.uvm.seq": ["uvm_sequence", "uvm_sequence_item", "uvm_sequencer", "uvm_driver", "uvm_monitor"],
            "std.uvm.phases": ["build_phase", "connect_phase", "run_phase", "check_phase", "report_phase"],
            "std.uvm.tlm": ["uvm_analysis_port", "uvm_analysis_export", "uvm_tlm_fifo", "uvm_tlm_analysis_fifo", "uvm_event"],
            "std.uvm.factory": ["uvm_factory", "create", "set_type_override", "set_inst_override", "create_component_by_name"],
            "std.uvm.report": ["uvm_report_handler", "uvm_report_server", "uvm_report_object", "uvm_report_info", "uvm_report_error"],
            "std.uvm.reg": ["uvm_reg", "uvm_reg_block", "uvm_reg_map", "uvm_reg_field", "uvm_reg_predictor"],
            "std.uvm.sequencer": ["uvm_sequencer_base", "uvm_sequencer_param_base", "uvm_push_sequencer", "uvm_sequencer"],
            "std.uvm.recorder": ["uvm_recorder", "uvm_tr_database", "uvm_tr_stream", "uvm_link", "uvm_text_recorder"],
            "std.uvm.callback": ["uvm_callback", "uvm_callbacks", "uvm_callback_iter", "uvm_add_callback", "uvm_remove_callback"],
            "std.uvm.pool": ["uvm_pool", "uvm_object_string_pool", "uvm_queue", "uvm_in_order_class_comparator"],
        },
    }

    def get_symbols(self, language: str, module: str) -> List[str]:
        """Get symbols for a specific module in a language."""
        lang_table = self._TABLES.get(language.lower(), {})
        return lang_table.get(module, [])

    def get_all_modules(self, language: str) -> Dict[str, List[str]]:
        """Get all registered modules and their symbols for a language."""
        return self._TABLES.get(language.lower(), {})

    def is_stdlib_module(self, language: str, module_name: str) -> bool:
        """Check if a module name belongs to the standard library of a language."""
        return module_name in self._TABLES.get(language.lower(), {})
