"""Duck-typed protocol shared by graph storage backends.

Both :class:`~batho.modules.graph.builder.codegraph.InMemoryGraph` and
:class:`~batho.modules.graph.builder.arrow_graph.ArrowGraph` implement this
surface, so post-processing and consumer code can operate on either backend
without isinstance checks.

Note on ``from_dict``: ``ArrowGraph.from_dict`` deviates by requiring an
additional ``staging_dir`` argument; it is therefore intentionally excluded
from this protocol.
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from batho.core.schemas import Entity, EntityType, Relationship


@runtime_checkable
class GraphBackend(Protocol):
    """Shared graph backend surface (write / read / mutation / lifecycle)."""

    # -- Attribute-style containers -------------------------------------
    # InMemoryGraph: plain dict/list attributes.
    # ArrowGraph: properties returning ArrowEntityView/ArrowRelView.
    entities: Any
    relationships: Any

    # -- Writes ----------------------------------------------------------
    def add_entity(self, entity: Entity) -> None: ...

    def add_entities_batch(self, entities: list[Entity]) -> None: ...

    def add_relationship(self, relationship: Relationship) -> None: ...

    def add_relationships_batch(self, relationships: list[Relationship]) -> None: ...

    # -- Reads -----------------------------------------------------------
    def get_entity(self, entity_id: str) -> Entity | None: ...

    def neighbors(self, entity_id: str, direction: str = "out") -> list[str]: ...

    def has_incoming_edges(self, entity_id: str) -> bool: ...

    def has_outgoing_edges(self, entity_id: str) -> bool: ...

    def get_all_nodes(self) -> list[str]: ...

    def entities_by_file(self, file_path: str) -> list[Entity]: ...

    def entities_by_type(self, entity_type: EntityType) -> list[Entity]: ...

    def get_rels_by_endpoint(self, entity_id: str) -> list[Relationship]: ...

    def degree_by_endpoint(self, entity_id: str) -> int: ...

    def entity_ids_by_type(self, entity_type: EntityType) -> list[str]: ...

    def root_entities(self) -> list[Entity]: ...

    # -- Mutations -------------------------------------------------------
    def update_entity(self, entity_id: str, entity: Entity) -> None: ...

    def update_relationships(self, relationships: list[Relationship]) -> None: ...

    def update_relationship(self, relationship: Relationship) -> None: ...

    def remove_node(self, entity_id: str) -> bool: ...

    def evict_file_graph(self, file_path: str) -> None: ...

    def enrich_from_storage_view(self, storage_view_data: dict[str, Any]) -> None: ...

    # -- Lifecycle -------------------------------------------------------
    def compact(self) -> None: ...

    def close(self) -> None: ...

    # -- Utility ---------------------------------------------------------
    def __len__(self) -> int: ...

    def __contains__(self, entity_id: str) -> bool: ...

    def stats(self) -> dict[str, Any]: ...

    def to_dict(self, *, view: str = "storage") -> dict[str, Any]: ...
